name: Release sbx

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:

  build-sbx:
    name: build-sbx
    runs-on: ubuntu-latest
    environment: sbx

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build and Push docker image
        run: |
          IMAGE_TAG="$PROJECT_NAME:v$VERSION$SUFFIX"
          docker build --file Dockerfile --build-arg SKIP_TESTS=true --build-arg ENVIRONMENT=sbx --tag $DOCKER_HUB_CLIENT_NAME/$IMAGE_TAG .
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push $DOCKER_HUB_CLIENT_NAME/$IMAGE_TAG
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_HUB_CLIENT_NAME: ${{ secrets.DOCKER_HUB_CLIENT_NAME }}
          PROJECT_NAME: ${{ 'dome-wallet-keycloak' }}
          VERSION: ${{ '1.0.0' }}
          SUFFIX: -SBX
